parameters:
- name: srcPath
  type: string
  default: '.'
- name: runStaticAnalysis
  type: boolean
  default: False

steps:
- script: |
    cd ${{ parameters.srcFolder }}
    mkdir build && cd build
    cmake ..
    make
  displayName: "Build SysinternalsEBPF binaries"

- script: |
    if [ ${{ parameters.runStaticAnalysis }} == True ]; then
      cd ${{ parameters.srcFolder }}
      rm -rf build && mkdir build && cd build
      scan-build cmake ..
      scan-build -v --status-bugs -o verifier_result --exclude libbpf make
    else
      echo "Skipping static code analysis."
    fi
  displayName: "Static analysis of SysinternalsEBPF source code"
